apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfrontend
  namespace: cust1
  labels:
    app: webfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfrontend
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
        - name: webfrontend
          image: 253490773985.dkr.ecr.ap-south-1.amazonaws.com/webfrontend:cust1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: webfrontend-config
          resources:
            requests:
              cpu: "20m"
              memory: "50Mi"
            limits:
              cpu: "50m"
              memory: "100Mi"
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/AuthBackEnd/logs
            - name: media
              mountPath: /var/www/html/AuthBackEnd/media
      volumes:
        - name: logs
          emptyDir: {}
        - name: media
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: webfrontend
  namespace: cust1
spec:
  selector:
    app: webfrontend
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80 
  type: ClusterIP 

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webfrontend-hpa
  namespace: cust1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webfrontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 3
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 30
          periodSeconds: 300