---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authbackend
  namespace: <CUSTOMER>
  labels:
    app: authbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authbackend
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: authbackend
    spec:
      containers:
        - name: authbackend
          image: 253490773985.dkr.ecr.ap-south-1.amazonaws.com/authbackend:<CUSTOMER>
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: authbackend-config
          resources:
            requests:
              cpu: "50m"
              memory: "2024Mi"
            limits:
              cpu: "200m"
              memory: "3024Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /api/lovs/check/
          #     port: 80
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /api/lovs/check/
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          volumeMounts:
            - name: logs
              mountPath: /var/www/html/AuthBackEnd/logs
            - name: media
              mountPath: /var/www/html/AuthBackEnd/media
      volumes:
        - name: logs
          emptyDir: {}
        - name: media
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: authbackend
  namespace: <CUSTOMER>
spec:
  selector:
    app: authbackend
  ports:
    - protocol: TCP
      port: 80       # ALB talks to this port
      targetPort: 80 # Container port
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authbackend-hpa
  namespace: <CUSTOMER>
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authbackend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 3
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
        - type: Percent
          value: 30
          periodSeconds: 300
